### ISSUE TITLE
youtube video background: parameter for what to do after the end of the video

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#11]
Via the YouTube iframe API, is it possible to get the event that the video has ended? If so, is it possible to set an action via the parameters to be triggered? Such as "next slide"?

**Comment by justmarkup** [comment]
Yes, I added a custom event which gets triggered when a video is finished and which you can listen:

For example if you want to show the next slide on finish you can use:

`document.querySelector('html').addEventListener('videoFinished', function(e) {
    Reveal.next();
}, false);`

**Comment by justmarkup** [comment]
Can not reproduce this in Chrome or Firefox, see Screenshot:

![overview](https://cloud.githubusercontent.com/assets/795237/26068987/c522b596-399f-11e7-9074-6fe56bfe7dc7.png)

In which browser does this happen? Can you please post a screenshot/screenshare.

**Comment by MiczFlor** [comment]
Would it be possible to make this a parameter that could make `data-background-youtube-video-rel` redundant?
Like:
`data-background-youtube-video-finished` options:

- "0" (default) do nothing
- "related" shows related videos, recommended by YouTube
- "nextSlide" moves forward to the next slide in reveal.js

.. and there might be other things (like load external URL) at a later stage as options?

**Comment by justmarkup** [comment]
Added the three options for now but yes we can add more later if needed.
