### ISSUE TITLE
Overview map with youtube background iframe plugin broken

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#12]
You can get an overview of the slideshow in reveal.js when you press "Escape". Then, the slide "zooms out" and you see an overview of all the slides like post it notes. Very nice. 
The youtube background iframe plugin acts weirdly when moving out. The videos are playing in the correct, smaller size, but outside the frame where they should be playing.

**Comment by justmarkup** [comment]
Can not reproduce this in Chrome or Firefox, see Screenshot:

![overview](https://cloud.githubusercontent.com/assets/795237/26068987/c522b596-399f-11e7-9074-6fe56bfe7dc7.png)

In which browser does this happen? Can you please post a screenshot/screenshare.

**Comment by MiczFlor** [comment]
The video has to be playing, then you hit the "Escape" key. See my example here:
![yt-overview](https://cloud.githubusercontent.com/assets/1876216/26128596/37f14a04-3a8d-11e7-8440-1341dc3fd3c4.png)

**Comment by justmarkup** [comment]
Sorry, but still not sure what about the requirements here.

1) What should happen when opening the overview map when on a page with no background youtube video?
2) What should happen when opening the overview map when on a page with a background youtube video and the video paused?
3) What should happen when opening the overview map when on a page with a background youtube video and the video playing?

**Comment by MiczFlor** [comment]
In the image above you can see the overview page where the Kottbusser Tor video is playing. 
The Kottbusser Tor slide is in the middle of the screen. But the video is playing at the right of the screen.
The size is correct, so in general it seems to work, just the position is off.

Answering your questions:
1. What should happen when opening the overview map when on a page with no background youtube video? - the slide is in the middle of the overview page. You can try it by hitting 'escape' while in the slide show. Then you can navigate with the cursor keys. If you hit 'escape' again, the center slide will zoom in to full page view again.

2. What should happen when opening the overview map when on a page with a background youtube video and the video paused? - ideally, the video is just smaller and on the appropriate slide in the middle of the page.

3. What should happen when opening the overview map when on a page with a background youtube video and the video playing? - ideally, the video pauses and then see point 2.

The most important part is that the video is not in the wrong place. I assume catching the escape key in the plugin complicates matters. If easier: just hide the video when in overview mode and just show the slides.

**Comment by justmarkup** [comment]
Background video are now correctly positioned when in overview mode.

**Comment by MiczFlor** [comment]
The issue still prevails. Yes, when you are on the video and the video is playing and you go into overview, the video is in the right place.
But try this: 

- go to the first video tests/test-youtube-iframe-bg-reveal.js.html#/1
- go into overview (hit escape)
- stay in overview and go two slides to the right, going to the next video. 

This will still show in the wrong position (see attached image)
![video in wrong place in overview when using navigation](https://user-images.githubusercontent.com/1876216/27076017-42b7b41e-502c-11e7-97a5-9e037c9d05df.png)

**Comment by MiczFlor** [comment]
If fixing this is too complicated, better to not play the videos in the overview at all.

**Comment by justmarkup** [comment]
Video are now hidden in the overview.
