### ISSUE TITLE
Show Modal Popup after Time Delay

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#14]
The user story: in revealjs the user goes to a new slide. After time delay X, a modal jumps in front of the screen with video content. The user can close the video by pressing [x] or [close] or the like.

- [ ] This can live inside the area that revealjs uses out of the box. No need to stretch it to fill the screen. 
- [ ] It should sit in the middle of the monitor and the proportions should be accurate (as in 16:9 for example).
- [ ] Important: needs to work on the desktop and mobile view.

Here is an article that looks very similar to what we need (without the video in the modal):
https://www.sitepoint.com/show-modal-popup-after-time-delay/

Would be nice to have (as in version 2):
- [ ] set delay as a value in the section of the slide
- [ ] set modal-video ID and the other parameters that we have in youtube-iframe-background here as well
- [ ] parameter which sets the appearance of the modal: appear or slide in from left, right, top, bottom (like the usual, annoying newsletter sign ups)
- [ ] change the speed how fast or slow the video slides into the page

**Comment by MiczFlor** [comment]
Duplicate from issue #16

**Comment by MiczFlor** [comment]
Hi @justmarkup 

I found and opened this issue again. My question: since the slidein.js plugin now basically has a modal outside of the slides, would it be possible to not write a second plugin, but simply add configuration to this plugin?
Have a look at the original outline.
If we were to specify

- [ ] appearance (slide in from bottom, from top, left right, or simply appear)
- [ ] final state margin from top, left, right, bottom; e.g. slide in from bottom right now would be something like (bottom 0%, left 0%, right 0%, top 30%) a modal in the middle would be like (top, left, right, bottom 20%)

**Comment by justmarkup** [comment]
The slidein transition and where the modal should appear is defined in CSS so I don't think we need additional parameters here. With some small changes in the CSS you could move in the modal from whatever side you want and stop it at whatever position you want.
