### ISSUE TITLE
Advertisment style slidein from bottom as modal

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#15]
This should be a separate plugin for `revealjs`, named `timeline-slidein.js`

## What happens?

1. The user goes to the slide
2. after a set time, a slider appears from the bottom of the page, containing HTML (delay)
3. the user can close the slider by pressing [x]
4. The slider disappears again after a set time (duration)

This is a good impression of what the slide in should look like. It does not have the disappearing built in.
[http://jsfiddle.net/jme11/51wro3fc/](http://jsfiddle.net/jme11/51wro3fc/) (and, yes, I know this is built on Bootstrap 2.3 :) just as an example...).

## params in section tag

The controls in the section tag should (could) be:
- [x] `timeline-slidein-delay` -> the delay between slide loading and slidein of modal in miliseconds
- [x] `timeline-slidein-duration` -> the duration until the modal slides out again in miliseconds

Regarding the HTML that is displayed, the section tag should contain a div that has a class similar to timeline-slidein which is invisible and slides in once the delay has passed and then out again if duration is set.

## If params aren't set

- [x] if `timeline-slidein-delay` is not set, the value is set to 500
- [x] if `timeline-slidein-duration` is not set, the value is set to 5000

**Comment by justmarkup** [comment]
Hi @MiczFlor,

see /tests/test-timeline-slidein.js.html for an example.
