### ISSUE TITLE
Slidein plugin on mobile devices: must lock to bottom

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#18]
See attached screenshot. This is just a smaller browser window, but I assume the mobile view might have the same problem. 
The modal should slide in from the bottom and stick to the bottom. 
Revealjs is already changing font sizes, etc. This is all fine and it is as it is.
But the stopping point should be the bottom of the page.

![reveal-modal-responsive](https://cloud.githubusercontent.com/assets/1876216/26520982/f1da712c-42dd-11e7-8e0e-4059d2707330.png)

**Comment by justmarkup** [comment]
This is a bit complicated because of all the transform happening inside the slides wrapper. Therefore I moved the modal outside of this so it always sticks to the bottom.
