### ISSUE TITLE
Slidein plugin without parameters: model jumps up and then to bottom

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#19]
If you go through the slides of the file `tests/test-timeline-slidein.js.html`, the second slide has no parameters set in the section tag.
On this slide, the modal jumps up first and then back down to the bottom. Hard to put into words :)
Seen on Ubuntu Firefox and Ubuntu Chromium.

**Comment by justmarkup** [comment]
This should be fixed as part of #18 - please test again.
