### ISSUE TITLE
full screen for youtube backround video

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#2]
A youtube background video, using the new plugin [background-youtube-video.js](https://github.com/Inkmap/WebDocCanvas/blob/master/vendor/revealjs/plugin/background-youtube-video/background-youtube-video.js), should accept a parameter similar to the [CSS3 background-size parameter](https://www.w3schools.com/cssref/css3_pr_background-size.asp).

cover - Scale the background video to be as large as possible so that the background area is completely covered by the background video. Some parts of the background video may not be in view within the background positioning area. This means that on a smartphone, held upright, the video will lose a lot of left and right off screen, but will reach from top to bottom.

contain - Scale the video to the largest size such that both its width and its height can fit inside the content area (this is the behaviour the plugin already has). This means that on a smartphone, held upright, the video will have a lot of black on top and bottom.

**Comment by justmarkup** [comment]
@MiczFlor this is not possible as the video always keeps the aspect ratio of 16/9 when using the youtube iframe api.

**Comment by MiczFlor** [comment]
Is it possible to trigger the "fullscreen" button - which is showing in the video - via the API? Then this could either result in an "autotrigger" on load or ready state. Or it could become an exposed control option, see ticket [https://github.com/Inkmap/WebDocCanvas/issues/4](https://github.com/Inkmap/WebDocCanvas/issues/4)

**Comment by justmarkup** [comment]
Yes, this is possible, will implement this as part of #4
