### ISSUE TITLE
'not a function' for youtube video background stopVideo

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#28]
In test-youtube-iframe-bg-reveal.js.html when I open the console and load the document, I get the waring (in Firefox under inspect element):
TypeError: backgroundYoutubeVideoPlayers[videoId].stopVideo is not a function[Learn More]

Linking the error here: 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_function

**Comment by justmarkup** [comment]
Added check to avoid the warning, please retest.
