### ISSUE TITLE
YouTube player div blocks menu navigation

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#29]
When you slide in the navigation menu from the left (use hamburger icon at bottom left), at the top of the menu you can click to switch tabs in the menu or close the menu.

The video player icons of the youtube iFrame video are positioned at the top and wrapped in a div which covers the entire top, making the menu tabs only clickable at the very bottom of each item.

See attached image to make it more clear: the div spreads all the way to the left.

![reveal-yt-inspect-menu](https://user-images.githubusercontent.com/1876216/27967839-daac24e6-6344-11e7-9a75-a649c77abd5f.png)

**Comment by justmarkup** [comment]
Restricted the width of the video controls so all items in sidebar are still clickable and usable.
