### ISSUE TITLE
Controls for background videos

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#4]
A slide with a youtube background video, using the new plugin [background-youtube-video.js](https://github.com/Inkmap/WebDocCanvas/blob/master/vendor/revealjs/plugin/background-youtube-video/background-youtube-video.js), should be able to feature controls in the same slide to control the video.

Toggle audio: on/off
Toggle play: play/pause
Reload (i.e. start from beginning)

Nice example for toggle Play / Pause was done in this [theme](https://revolthemes.net/demo/opekkha/html/index2.html)

**Comment by justmarkup** [comment]
Also add an control to toggle fullscreen mode as mentioned in #2

**Comment by justmarkup** [comment]
First version is ready:

- [x] Audio control
- [x] Play/Stop control
- [x] Reload button
- [x] Toggle fullscreen

@MiczFlor Please have a look if this is what you are looking for. We will need some design love for next version.

**Comment by MiczFlor** [comment]
Looking awesome. For the controls, I suggest to load icons from the material icons collection:
- Audio OFF: https://materialdesignicons.com/icon/volume-off
- Audio ON: https://materialdesignicons.com/icon/volume-high
- Playing: https://materialdesignicons.com/icon/play
- Pausing: https://materialdesignicons.com/icon/pause
- Reload: https://materialdesignicons.com/icon/reload
- Fullscreen: https://materialdesignicons.com/icon/fullscreen

Would be nice to specify the colour in CSS for fill and background - and possibly border?
Generally, I think white on black will work for now.

**Comment by justmarkup** [comment]
Okay, the controls now use the svg icons. At the moment there are white icons on black background but you can change this in CSS, eg. red icon on white background:

`.background-youtube-video-controls div {
  background: #fff;
  fill: red;
}`
