### ISSUE TITLE
More than one video in background creates problems with reloading slides.

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#5]
A slideshow using youtube background videos with [background-youtube-video.js](https://github.com/Inkmap/WebDocCanvas/blob/master/vendor/revealjs/plugin/background-youtube-video/background-youtube-video.js), creates a problem. 

In the HTML file [demo-youtube-iframe-bg-reveal.js.html](https://github.com/Inkmap/WebDocCanvas/blob/master/demo-youtube-iframe-bg-reveal.js.html), there are two videos in the background. When you use the navigation (keyboard shortcuts or arrows) and go to the last slide with the second video (U1 Görlitzer Bahnhof), after this started playing, going back will show the title image of the previous video (U8 Kottbusser Tor).

I can reproduce this in Firefox and Chromium.

**Comment by justmarkup** [comment]
Good catch! It is fixed now, please retest.

**Comment by MiczFlor** [comment]
Works like a charm :1st_place_medal:
