### ISSUE TITLE
YouTube video iframe: pass parameters to show / hide elements from video

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#6]
A slide with a youtube background video, using the new plugin [background-youtube-video.js](https://github.com/Inkmap/WebDocCanvas/blob/master/vendor/revealjs/plugin/background-youtube-video/background-youtube-video.js), needs to be customized. This means that the following options can be set to show or hide:

- [x] Title of the video
- [ ] Progress bar
- [x] Video suggestions at the end of the video
- [ ] Sharing options
- [ ] Info button

**Comment by justmarkup** [comment]
I added options to show/hide the title and the related videos at the end. For the other I couldn't find an option defined in the[ youtubue API](https://developers.google.com/youtube/player_parameters?playerVersion=HTML5) 

title:
default is hidden
add data-background-youtube-video-showinfo="1" to show it

related videos:
default is hidden
add data-background-youtube-video-rel="1" to show it
