### ISSUE TITLE
YouTube iframe video on mobile devices: different control status

### ISSUE THREAD

**Issue by MiczFlor** [Inkmap/Docmint#7]
On a mobile device, a slide with a youtube background video, using the new plugin [background-youtube-video.js](https://github.com/Inkmap/WebDocCanvas/blob/master/vendor/revealjs/plugin/background-youtube-video/background-youtube-video.js) is not playing automatically. See [Mobile auto playback and scripted playback](https://developers.google.com/youtube/iframe_api_reference?hl=en#Mobile_considerations).

Currently, tested on iOS
- the slide loads, shows the image of the video but does not load the video. 
- the player control says "playing" but it does not play
- touching the "playing" control, the video does start playing, loading the native player correctly.

Desired behavior would be: for mobile devices, show "paused" in the player controls.
And (possibly...?) hide all other controls, because audio on / off can not be toggled via the controls anyway once the native video player is loaded.

**Comment by justmarkup** [comment]
Since iOS 10 you can also play videos inline like on Android. I set the playsinline attribute to true, please test again with a device running iOS 10. It should now start automatically there.
